### ISSUE TITLE
` python main.py --help` throws error 

### ISSUE THREAD

**Issue by jackiekazil** [Open-Source-Software-Neighborhood-Watch/deps2repos#13]
Following the install instructions -- I get to `python main.py --help` and get the following error when trying to pip install. 
```
Traceback (most recent call last):
  File ".../deps2repos/main.py", line 6, in <module>
    from bioconda import generate_bioconda_source_links
  File ".../deps2repos/bioconda.py", line 6, in <module>
    from bioconda_utils.recipe import Recipe
ModuleNotFoundError: No module named 'bioconda_utils'
```

**Comment by jspeed-meyers** [comment]
@jackiekazil, I think the README is wrong. The readme seems to suggest that the bioconda installation is not necessary. It currently is, though this could be changed. To follow the bioconda installation, follow the installation instructions: https://github.com/Open-Source-Software-Neighborhood-Watch/deps2repos/blob/main/BIOCONDA-README.md

Alternatively, the current codebase can be used if you comment out these lines in main:

```python
from bioconda import generate_bioconda_source_links
```

and

```python
    # parse bionconda directory containing meta.yamls and return source links
    if args.bioconda:
        links = generate_bioconda_source_links(args.bioconda)
        for link in links:
            print(link)
```

Sorry for the trouble! PR's are welcome.

**Comment by jspeed-meyers** [comment]
@jackiekazil, I think the PR I merged fixed this.

**Comment by jackiekazil** [comment]
@jspeed-meyers ty
